import random
import numpy as np
from super_tictactoe.env import SuperTicTacToeEnv
from super_tictactoe.heuristics import stronger_heuristic, counter_heuristic, blocking_agent


# Pairs used to generate positions.  Mix ensures diversity:
# stronger vs stronger  → dense, balanced tactical positions
# counter vs stronger   → P1 is behind; tests defensive response
# stronger vs counter   → P1 is leading; tests offense consolidation
# blocking vs stronger  → P1 weaker; trains surviving under fire
_PAIRS = [
    (stronger_heuristic, stronger_heuristic),
    (counter_heuristic,  stronger_heuristic),
    (stronger_heuristic, counter_heuristic),
    (blocking_agent,     stronger_heuristic),
]
_WEIGHTS = [0.5, 0.2, 0.2, 0.1]


def _is_interesting(env: SuperTicTacToeEnv) -> bool:
    """True if the position has tactical value: threats are present or board is developed."""
    if env.done:
        return False
    pieces = int(np.sum(env.board != 0))
    if pieces >= 8:
        return True
    return (env._count_threats(1) + env._count_threats(2)) >= 1


def generate_position_pool(
    n_positions: int = 500,
    min_steps: int = 4,
    max_steps: int = 14,
    success_rate: float = 0.5,
) -> list:
    """
    Return a list of (board, current_player) tuples representing mid-game positions.

    Each position is generated by running min_steps–max_steps moves of a heuristic
    pair and kept only if _is_interesting() passes.  Up to 8× n_positions attempts
    are made; if fewer interesting positions are found, the smaller pool is returned.
    """
    env = SuperTicTacToeEnv(success_rate=success_rate)
    positions = []

    for _ in range(n_positions * 8):
        if len(positions) >= n_positions:
            break
        env.reset()
        steps = random.randint(min_steps, max_steps)
        hA, hB = random.choices(_PAIRS, weights=_WEIGHTS, k=1)[0]

        for _ in range(steps):
            if env.done:
                break
            h = hA if env.current_player == 1 else hB
            env.step(h(env))

        if _is_interesting(env):
            positions.append((env.board.copy(), int(env.current_player)))

    return positions
